In [1]:
import MDAnalysis as mda
from MDAnalysis.analysis import align
from openmm.app import* 
import sys
import os
sys.path.append(os.path.abspath('../'))
from src.useful_functions import*


/scratch/htc/fsafarov/openmm_ff/lib/python3.12/site-packages/Bio/Application/__init__.py:39: BiopythonDeprecationWarning: The Bio.Application modules and modules relying on it have been deprecated.

Due to the on going maintenance burden of keeping command line application
wrappers up to date, we have decided to deprecate and eventually remove these
modules.

We instead now recommend building your command line and invoking it directly
with the subprocess module.
  warnings.warn(


In [2]:
read_dirs_paths('dir_paths.txt', globals())

Created variables:
inp_dir = /scratch/htc/fsafarov/2cm2_simulation/md2/input/
out_trajectories1 = /scratch/htc/fsafarov/2cm2_simulation/md2/output_[0-5]*/trajectories/
out_trajectories2 = /scratch/htc/fsafarov/2cm2_simulation/md2/output_[0-5]*/trajectories/openmm_files/
out_initial_states = /scratch/htc/fsafarov/2cm2_simulation/md2/output_0/trajectories/openmm_files/initial_states/
out_final_states = /scratch/htc/fsafarov/2cm2_simulation/md2/output_[0-5]*/trajectories/openmm_files/final_states/
out_isokann = /scratch/htc/fsafarov/2cm2_simulation/md2/output/isokann/
out_mokito = /scratch/htc/fsafarov/2cm2_simulation/md2/output/mokito/


In [4]:
# Same structure for all trajectories
ref = mda.Universe(inp_dir + 'pdbfile_water.pdb')

traj_files, folders = multiple_dirs(out_trajectories2, fetch_files = True)
print(len(folders))
# trj = []
for i in range(len(folders)):
    trj.append(mda.Universe(inp_dir + 'pdbfile_water.pdb', os.path.join(folders[i], 'trajectory_water_combined.dcd')))
    alignment = align.AlignTraj(trj[i], ref, select='protein and name CA', filename= os.path.join(folders[i], 'alignedtraj_rmsfit_CA_only.dcd'))
    alignment.run()


6


In [ ]:
fs_files, fs_folders = multiple_dirs(out_final_states, fetch_files = True)
for fs_folder in fs_folders:
    for fs_file in fs_files[fs_folder]:
        try:
            trj = mda.Universe(inp_dir + 'pdbfile_water.pdb', os.path.join(fs_folder, fs_file))
        except:
            continue
        alignment = align.AlignTraj(trj, ref, select='protein and name CA', filename= os.path.join(fs_folder, fs_file.replace('.dcd', '_aligned.dcd')))
        alignment.run()

In [7]:
import MDAnalysis as mda
from openmm.app import* 

ref = mda.Universe('/scratch/htc/fsafarov/2cm2_simulation/md2/input/pdbfile_water.pdb')
calphas = ref.select_atoms("name CA and resname ASP and resid 11")
n_calpha = calphas.n_atoms
bb_idx = calphas.indices

In [8]:
import numpy as np
lig = ref.select_atoms("resname KB8 and not element H") 
n_lig = lig.n_atoms
kb8_idx = lig.indices

sel_idx = np.concatenate([bb_idx, kb8_idx])
sel_idx

array([ 162, 4601, 4602, 4603, 4604, 4605, 4606, 4607, 4608, 4609, 4610,
       4611, 4612, 4613, 4614, 4615, 4616, 4617, 4618, 4619, 4620, 4621])

In [3]:
from scipy.spatial.distance import pdist

In [9]:
trj= mda.Universe(inp_dir + 'pdbfile_water.pdb', os.path.join(folders[0], 'trajectory_water_combined.dcd'))
trj.trajectory[137]
atoms   =  trj.atoms[sel_idx]
atom2_coords = atoms.positions
box = trj.trajectory.ts.dimensions
box

array([90.604515, 90.604515, 90.604515, 90.      , 90.      , 90.      ],
      dtype=float32)

In [10]:
ref.dimensions

array([90.605, 90.605, 90.605, 90.   , 90.   , 90.   ], dtype=float32)

In [11]:
rel_coords = np.array([[0,70]])

In [13]:
len(rel_coords[0])

2